---
abstract: 'Alternate Data Localization API'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.94
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Localize
no_index:
  directory:
    - inc
    - t
    - tools
    - xt
recommends:
  BerkeleyDB: 0
  Config::Any: 0
requires:
  Encode: 0
  I18N::LangTags: 0
  I18N::LangTags::Detect: 0
  Log::Minimal: 0.14
  Module::Load: 0
  Module::Pluggable::Object: 0
  Moo: 1.000008
  MooX::Types::MooseLike::Base: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/lestrrat/Data-Localize.git
version: 0.00025
