---
abstract: 'Alternate Data Localization API'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Localize
no_index:
  directory:
    - inc
    - t
    - tools
    - xt
recommends:
  BerkeleyDB: 0
  Moose: 0
requires:
  Any::Moose: 0
  Encode: 0
  I18N::LangTags: 0
  I18N::LangTags::Detect: 0
  Module::Pluggable::Object: 0
  Mouse: 0.19
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com//lestrrat/Data-Localize.git
version: 0.00013_02
